### ISSUE TITLE
@bhargav-007 Currently there is no such functionality to reset rating. I will soon add it.

### ISSUE THREAD

**Issue by Swapnali1010** [jitendradp/ngx-star-rating#12]
@bhargav-007 Currently there is no such functionality to reset rating. I will soon add it.

_Originally posted by @jitendradp in https://github.com/jitendradp/ngx-star-rating/issues/2#issuecomment-583949245_

Please provide reset function as ngmodal values get changed but the selected star mark design remains the same

**Comment by jitendradp** [comment]
@Swapnali1010  I have published an updated package. You can upgrade the package using `npm i ngx-star-rating@2.0.0` command
