### ISSUE TITLE
Regards, I need to update angular to version 12, but it throws me this error:

### ISSUE THREAD

**Issue by josueperezf** [jitendradp/ngx-star-rating#15]
1. Package "ngx-star-rating" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0" (extended), would install "12.1.5").

2.  Package "ngx-star-rating" has an incompatible peer dependency to "@angular/core" (requires "^9.0.0" (extended), would install "12.1.5").12, pero me arroja este error:

**Comment by jitendradp** [comment]
@josueperezf  I have updated the package. You can update the package and try it.

Thanks,
Jitendra Prajapati
