### ISSUE TITLE
showing a different icon.

### ISSUE THREAD

**Issue by Shiru-kun** [jitendradp/ngx-star-rating#17]
Hi, hope you are doing fine, i just added this package in my project, it was working fine but now i see a different icon while expected to see stars. 
![image](https://user-images.githubusercontent.com/54008441/144666550-9b263cc8-10e4-4bc7-add1-0f77e7625686.png)

**Comment by jitendradp** [comment]
@Shiru-kun  I think you used different font so that it's not displaying stars, could you please share URL so I can test check it.

**Comment by Slavrix** [comment]
It would be cool if it could be extended to allow us to use an icon from a font already installed in our system or a custom icon even.
