### ISSUE TITLE
Reset rating count.

### ISSUE THREAD

**Issue by bhargav-007** [jitendradp/ngx-star-rating#2]
How do I reset the rating count after submitting the form? is there any function to reset rating count ?

**Comment by jitendradp** [comment]
@bhargav-007 Currently there is no such functionality to reset rating. I will soon add it.

**Comment by nickykapur** [comment]
This component is really nice. but the reset was needed.

**Comment by nickykapur** [comment]
> This component is really nice. but the reset was needed.

So not sure if there is more support to this add-on?

**Comment by jitendradp** [comment]
@bhargav-007  @nickykapur  I have published an updated package. You can upgrade the package using `npm i ngx-star-rating@2.0.0` command

**Comment by bhargav-007** [comment]
@jitendradp thank you very much..!
